Adopt Project Manager
This also removes the Probot `_extends` usage, as that’s subsumed by Project
Manager.

diff --git a/scripts/sync-template b/scripts/sync-template
--- a/scripts/sync-template
+++ b/scripts/sync-template
@@ -13,19 +13,19 @@ Usage:
 
   Updates the current project with the latest from the upstream template.
 
-  PROJECT_TYPE is the name of the template to sync. If it’s not provided, an
-               attempt will be made to read it from the ‘type.name’ field in the
-               mustache YAML file if it exists.
+  PROJECT_TYPE is the name of the template to sync. If it’s not provided, we try
+               to read it from the ‘type.name’ field in the mustache YAML file
+               if it exists.
 
   This script looks for .config/mustache.yaml in the repository root. If found,
   it will apply template substitution, but this will still run without it.
 
   Caveats:
-  - this does not remove files that have been removed from the template since
+  - this doesn’t remove files that have been removed from the template since
     the last update and
   - this applies mustache if the expected .config/mustache.yaml exists in the
-    repo, but that doesn’t yet support renaming files, so some may need to be
-    manually renamed after they’re created.
+    repository, but that doesn’t yet support renaming files, so some may need to
+    be manually renamed after they’re created.
 EOF
 }
 
@@ -57,7 +57,7 @@ if [[ ! -v project_type ]]; then
   if [[ -f ${mustache_file} ]]; then
     project_type="$(yq '.type.name' "${mustache_file}")"
   else
-    echo "Unable to determine project type." >&2
+    echo "Unable to find project type." >&2
     usage
     exit 1
   fi
